#!/bin/bash
# ===============================================================================
#                    SCRIPT DE INSTALAÇÃO DE ALIASES AUTOMÁTICOS
# ===============================================================================
# Data: 23 de julho de 2025
# Descrição: Script para instalar e configurar aliases úteis no Zsh

echo "🚀 Instalando aliases automáticos para Zsh..."

# Verificar se o arquivo .zsh_aliases existe
if [ ! -f "$HOME/.zsh_aliases" ]; then
    echo "📁 Copiando arquivo de aliases..."
    cp .zsh_aliases "$HOME/.zsh_aliases"
    echo "✅ Arquivo .zsh_aliases copiado para $HOME/"
else
    echo "⚠️  Arquivo .zsh_aliases já existe. Fazendo backup..."
    cp "$HOME/.zsh_aliases" "$HOME/.zsh_aliases.backup.$(date +%Y%m%d_%H%M%S)"
    cp .zsh_aliases "$HOME/.zsh_aliases"
    echo "✅ Arquivo atualizado e backup criado"
fi

# Verificar se a configuração já existe no .zshrc
if ! grep -q "source ~/.zsh_aliases" "$HOME/.zshrc"; then
    echo "🔧 Configurando .zshrc..."
    echo "" >> "$HOME/.zshrc"
    echo "# Carregar aliases personalizados" >> "$HOME/.zshrc"
    echo "if [ -f ~/.zsh_aliases ]; then" >> "$HOME/.zshrc"
    echo "    source ~/.zsh_aliases" >> "$HOME/.zshrc"
    echo "fi" >> "$HOME/.zshrc"
    echo "✅ Configuração adicionada ao .zshrc"
else
    echo "ℹ️  Configuração já existe no .zshrc"
fi

echo ""
echo "🎉 Instalação concluída!"
echo ""
echo "📋 ALIASES INSTALADOS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🤖 GITHUB COPILOT CLI:"
echo "  cop          - gh copilot suggest"
echo "  copgit       - gh copilot suggest --type git"
echo "  copgh        - gh copilot suggest --type gh"
echo "  copex        - gh copilot explain"
echo "  pergunta     - gh copilot suggest (em português)"
echo "  explica      - gh copilot explain (em português)"
echo ""
echo "📁 NAVEGAÇÃO:"
echo "  ..           - cd .."
echo "  ...          - cd ../.."
echo "  ll           - ls -alF --color=auto"
echo "  la           - ls -A --color=auto"
echo "  lsize        - ls por tamanho"
echo ""
echo "🔧 SISTEMA:"
echo "  sysinfo      - informações do sistema"
echo "  mem          - uso de memória"
echo "  disk         - uso de disco"
echo "  processes    - processos por CPU"
echo ""
echo "🌐 REDE:"
echo "  myip         - IP público"
echo "  localip      - IP local"
echo "  dnstest      - testar DNS"
echo "  pingtest     - ping para 8.8.8.8"
echo ""
echo "📦 PACOTES:"
echo "  install      - sudo apt install"
echo "  update       - sudo apt update && upgrade"
echo "  cleanup      - limpeza do sistema"
echo ""
echo "🎯 GIT:"
echo "  g            - git"
echo "  gs           - git status"
echo "  ga           - git add"
echo "  gc           - git commit"
echo "  gp           - git push"
echo "  gpl          - git pull"
echo ""
echo "🚀 DESENVOLVIMENTO:"
echo "  py           - python3"
echo "  ni           - npm install"
echo "  code         - code ."
echo ""
echo "💡 PRODUTIVIDADE:"
echo "  reload       - recarregar .zshrc"
echo "  aliases      - listar aliases"
echo "  clr          - clear"
echo ""
echo "🔧 FUNÇÕES ÚTEIS:"
echo "  mkcd <dir>   - criar e entrar em diretório"
echo "  backup <arquivo> - fazer backup com timestamp"
echo "  extract <arquivo> - extrair qualquer arquivo"
echo "  findlarge <tamanho> - encontrar arquivos grandes"
echo "  findtext <texto> - buscar texto em arquivos"
echo "  port <número> - ver uso de porta"
echo "  weather <cidade> - previsão do tempo"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔄 Para aplicar os aliases agora, execute:"
echo "   source ~/.zshrc"
echo ""
echo "🏠 Ou reinicie o terminal"
echo ""
echo "📚 Para ver todos os aliases disponíveis:"
echo "   aliases"
echo ""
echo "💡 Para testar o GitHub Copilot CLI:"
echo "   cop \"como ver arquivos por tamanho\""
echo ""
